export interface Artigo {
	idartigo: string | null,
    artigo: string,
    idmarca: number,
    idfornecedor: number,
    idcategoriaP: number,
    idfamilia: number,
    idsubfamilia: number,
    qt: number,
    stockloja: number,
    qtReservada: number,
    qtMin: number,
    custo: number,
    custoIVA: number,
    venda: number,
    vendaIVA: number,
    desconto: number,
    pvpWWW: number,
    margemAmadeus: number,
    vendaRevenda: number,
    IVA: number,
    peso: number,
    modelo: string,
    codigointerno: string,
    EAN: string,
    imgURL: string,
}